name: covi
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.1
  font_awesome_flutter: ^8.5.0
  google_fonts: ^0.3.10
  twitter_api: ^0.1.2
  firebase_core: ^0.4.3+1
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.4+2
  carousel_pro: ^1.0.0
  http: ^0.12.0+4
  firebase_auth:
  google_sign_in:
  flutter_bloc:
  equatable:
  meta:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
